name: SpectoLogic
favicon: null
layout_spectrum: 0.16641760291531682
typography_spectrum: 0.025014462880790234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.038703417871147394
  lightness: 0.1042766806203872
  saturation: 0.21417408529669046
  rhythmicContrast: 0.6006712971720845
purpose: []
